version: '3.8'


networks:
  my-network:
    driver: bridge
#    ipam:
#      config:
#        - subnet: 10.5.0.0/16


services:
  groceryapiproject:
#    image: "groceryBookingApiProject-1.0:latest"
#    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_UTL: jdbc:mysql://mysqldb:3306/grocery_repository?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - my-network
    depends_on:
      - mysqldb

  mysqldb:
    image: "mysql:5.7"
#    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: grocery_repository
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
#      MYSQL_USER: root
#      MYSQL_PASSWORD: root
    networks:
      - my-network
    volumes:
      - db_data:/var/lib/mysqldb

volumes:
  db_data:
